version: '3'
services:
  mysql-init:
    image: mysql:5.7
    command: /init-db.sh
    networks:
      - sc-net
    volumes:
      - ../auth/db:/sql/auth
      - ../gateway/gateway-admin/src/main/db:/sql/gateway
      - ../sysadmin/db:/sql/sysadmin
      - ./apollo/sql:/sql
      - ./init-db.sh:/init-db.sh
    environment:
      MYSQL_ROOT_PASSWORD: root123